//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.23 at 04:45:00 PM CDT 
//


package org.usd.edu.btl.betsconverter.GalaxyV1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActionsOptionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ActionsOptionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="from_data_table"/>
 *     &lt;enumeration value="from_param"/>
 *     &lt;enumeration value="from_file"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ActionsOptionType")
@XmlEnum
public enum ActionsOptionType {

    /**
     *
     */
    @XmlEnumValue("from_data_table")
    FROM_DATA_TABLE("from_data_table"),

    /**
     *
     */
    @XmlEnumValue("from_param")
    FROM_PARAM("from_param"),

    /**
     *
     */
    @XmlEnumValue("from_file")
    FROM_FILE("from_file");
    private final String value;

    ActionsOptionType(String v) {
        value = v;
    }

    /**
     *
     * @return
     */
    public String value() {
        return value;
    }

    /**
     *
     * @param v
     * @return
     */
    public static ActionsOptionType fromValue(String v) {
        for (ActionsOptionType c: ActionsOptionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
