//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.23 at 04:45:00 PM CDT 
//


package org.usd.edu.btl.betsconverter.GalaxyV1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FilterType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FilterType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="data_meta"/>
 *     &lt;enumeration value="param_value"/>
 *     &lt;enumeration value="static_value"/>
 *     &lt;enumeration value="unique_value"/>
 *     &lt;enumeration value="multiple_splitter"/>
 *     &lt;enumeration value="add_value"/>
 *     &lt;enumeration value="sort_by"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FilterType")
@XmlEnum
public enum FilterType {

    /**
     *
     */
    @XmlEnumValue("data_meta")
    DATA_META("data_meta"),

    /**
     *
     */
    @XmlEnumValue("param_value")
    PARAM_VALUE("param_value"),

    /**
     *
     */
    @XmlEnumValue("static_value")
    STATIC_VALUE("static_value"),

    /**
     *
     */
    @XmlEnumValue("unique_value")
    UNIQUE_VALUE("unique_value"),

    /**
     *
     */
    @XmlEnumValue("multiple_splitter")
    MULTIPLE_SPLITTER("multiple_splitter"),

    /**
     *
     */
    @XmlEnumValue("add_value")
    ADD_VALUE("add_value"),

    /**
     *
     */
    @XmlEnumValue("sort_by")
    SORT_BY("sort_by");
    private final String value;

    FilterType(String v) {
        value = v;
    }

    /**
     *
     * @return
     */
    public String value() {
        return value;
    }

    /**
     *
     * @param v
     * @return
     */
    public static FilterType fromValue(String v) {
        for (FilterType c: FilterType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
