//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.23 at 04:45:00 PM CDT 
//


package org.usd.edu.btl.betsconverter.GalaxyV1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParamType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ParamType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="text"/>
 *     &lt;enumeration value="integer"/>
 *     &lt;enumeration value="float"/>
 *     &lt;enumeration value="boolean"/>
 *     &lt;enumeration value="genomebuild"/>
 *     &lt;enumeration value="select"/>
 *     &lt;enumeration value="data_column"/>
 *     &lt;enumeration value="hidden"/>
 *     &lt;enumeration value="baseurl"/>
 *     &lt;enumeration value="file"/>
 *     &lt;enumeration value="data"/>
 *     &lt;enumeration value="drill_down"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ParamType")
@XmlEnum
public enum ParamType {

    /**
     *
     */
    @XmlEnumValue("text")
    TEXT("text"),

    /**
     *
     */
    @XmlEnumValue("integer")
    INTEGER("integer"),

    /**
     *
     */
    @XmlEnumValue("float")
    FLOAT("float"),

    /**
     *
     */
    @XmlEnumValue("boolean")
    BOOLEAN("boolean"),

    /**
     *
     */
    @XmlEnumValue("genomebuild")
    GENOMEBUILD("genomebuild"),

    /**
     *
     */
    @XmlEnumValue("select")
    SELECT("select"),

    /**
     *
     */
    @XmlEnumValue("data_column")
    DATA_COLUMN("data_column"),

    /**
     *
     */
    @XmlEnumValue("hidden")
    HIDDEN("hidden"),

    /**
     *
     */
    @XmlEnumValue("baseurl")
    BASEURL("baseurl"),

    /**
     *
     */
    @XmlEnumValue("file")
    FILE("file"),

    /**
     *
     */
    @XmlEnumValue("data")
    DATA("data"),

    /**
     *
     */
    @XmlEnumValue("drill_down")
    DRILL_DOWN("drill_down");
    private final String value;

    ParamType(String v) {
        value = v;
    }

    /**
     *
     * @return
     */
    public String value() {
        return value;
    }

    /**
     *
     * @param v
     * @return
     */
    public static ParamType fromValue(String v) {
        for (ParamType c: ParamType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
