//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.23 at 04:45:00 PM CDT 
//

package org.usd.edu.btl.betsconverter.GalaxyV1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Sanitizer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Sanitizer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="valid" type="{}Valid" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="sanitize" type="{}PermissiveBoolean" />
 *       &lt;attribute name="invalid_char" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Sanitizer", propOrder = {
    "valid"
})
public class Sanitizer {

    /**
     *
     */
    protected List<Valid> valid;

    /**
     *
     */
    @XmlAttribute(name = "sanitize")
    protected String sanitize;

    /**
     *
     */
    @XmlAttribute(name = "invalid_char")
    protected String invalidChar;

    /**
     * Gets the value of the valid property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valid property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValid().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Valid }
     * 
     * 
     * @return 
     */
    public List<Valid> getValid() {
        if (valid == null) {
            valid = new ArrayList<Valid>();
        }
        return this.valid;
    }

    /**
     * Gets the value of the sanitize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSanitize() {
        return sanitize;
    }

    /**
     * Sets the value of the sanitize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSanitize(String value) {
        this.sanitize = value;
    }

    /**
     * Gets the value of the invalidChar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvalidChar() {
        return invalidChar;
    }

    /**
     * Sets the value of the invalidChar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvalidChar(String value) {
        this.invalidChar = value;
    }

}
