//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.23 at 04:45:00 PM CDT 
//

package org.usd.edu.btl.betsconverter.GalaxyV1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="requirements" type="{}Requirements" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="parallelism" type="{}Parallelism" minOccurs="0"/>
 *         &lt;element name="command" type="{}Command"/>
 *         &lt;element name="configfiles" type="{}ConfigFiles" minOccurs="0"/>
 *         &lt;element name="outputs" type="{}Outputs" minOccurs="0"/>
 *         &lt;element name="inputs" type="{}Inputs" minOccurs="0"/>
 *         &lt;element name="tests" type="{}Tests" minOccurs="0"/>
 *         &lt;element name="stdio" type="{}Stdio" minOccurs="0"/>
 *         &lt;element name="help" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="code" type="{}Code" minOccurs="0"/>
 *         &lt;element name="uihints" type="{}UIhints" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" default="1.0.0" />
 *       &lt;attribute name="hidden" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="tool_type" type="{}ToolTypeType" />
 *       &lt;attribute name="URL_method" type="{}URLmethodType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "tool")
public class Tool {

    /**
     *
     */
    protected Requirements requirements;

    /**
     *
     */
    protected String description;

    /**
     *
     */
    protected Parallelism parallelism;

    /**
     *
     */
    @XmlElement(required = true)
    protected Command command;

    /**
     *
     */
    protected ConfigFiles configfiles;

    /**
     *
     */
    protected Outputs outputs;

    /**
     *
     */
    protected Inputs inputs;

    /**
     *
     */
    protected Tests tests;

    /**
     *
     */
    protected Stdio stdio;

    /**
     *
     */
    protected String help;

    /**
     *
     */
    protected Code code;

    /**
     *
     */
    protected UIhints uihints;

    /**
     *
     */
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     *
     */
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     *
     */
    @XmlAttribute(name = "version")
    protected String version;

    /**
     *
     */
    @XmlAttribute(name = "hidden")
    protected Boolean hidden;

    /**
     *
     */
    @XmlAttribute(name = "tool_type")
    protected ToolTypeType toolType;

    /**
     *
     */
    @XmlAttribute(name = "URL_method")
    protected URLmethodType urlMethod;

    /**
     * Gets the value of the requirements property.
     * 
     * @return
     *     possible object is
     *     {@link Requirements }
     *     
     */
    public Requirements getRequirements() {
        return requirements;
    }

    /**
     * Sets the value of the requirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link Requirements }
     *     
     */
    public void setRequirements(Requirements value) {
        this.requirements = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the parallelism property.
     * 
     * @return
     *     possible object is
     *     {@link Parallelism }
     *     
     */
    public Parallelism getParallelism() {
        return parallelism;
    }

    /**
     * Sets the value of the parallelism property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parallelism }
     *     
     */
    public void setParallelism(Parallelism value) {
        this.parallelism = value;
    }

    /**
     * Gets the value of the command property.
     * 
     * @return
     *     possible object is
     *     {@link Command }
     *     
     */
    public Command getCommand() {
        return command;
    }

    /**
     * Sets the value of the command property.
     * 
     * @param value
     *     allowed object is
     *     {@link Command }
     *     
     */
    public void setCommand(Command value) {
        this.command = value;
    }

    /**
     * Gets the value of the configfiles property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigFiles }
     *     
     */
    public ConfigFiles getConfigfiles() {
        return configfiles;
    }

    /**
     * Sets the value of the configfiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigFiles }
     *     
     */
    public void setConfigfiles(ConfigFiles value) {
        this.configfiles = value;
    }

    /**
     * Gets the value of the outputs property.
     * 
     * @return
     *     possible object is
     *     {@link Outputs }
     *     
     */
    public Outputs getOutputs() {
        return outputs;
    }

    /**
     * Sets the value of the outputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Outputs }
     *     
     */
    public void setOutputs(Outputs value) {
        this.outputs = value;
    }

    /**
     * Gets the value of the inputs property.
     * 
     * @return
     *     possible object is
     *     {@link Inputs }
     *     
     */
    public Inputs getInputs() {
        return inputs;
    }

    /**
     * Sets the value of the inputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Inputs }
     *     
     */
    public void setInputs(Inputs value) {
        this.inputs = value;
    }

    /**
     * Gets the value of the tests property.
     * 
     * @return
     *     possible object is
     *     {@link Tests }
     *     
     */
    public Tests getTests() {
        return tests;
    }

    /**
     * Sets the value of the tests property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tests }
     *     
     */
    public void setTests(Tests value) {
        this.tests = value;
    }

    /**
     * Gets the value of the stdio property.
     * 
     * @return
     *     possible object is
     *     {@link Stdio }
     *     
     */
    public Stdio getStdio() {
        return stdio;
    }

    /**
     * Sets the value of the stdio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stdio }
     *     
     */
    public void setStdio(Stdio value) {
        this.stdio = value;
    }

    /**
     * Gets the value of the help property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelp() {
        return help;
    }

    /**
     * Sets the value of the help property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelp(String value) {
        this.help = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link Code }
     *     
     */
    public Code getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link Code }
     *     
     */
    public void setCode(Code value) {
        this.code = value;
    }

    /**
     * Gets the value of the uihints property.
     * 
     * @return
     *     possible object is
     *     {@link UIhints }
     *     
     */
    public UIhints getUihints() {
        return uihints;
    }

    /**
     * Sets the value of the uihints property.
     * 
     * @param value
     *     allowed object is
     *     {@link UIhints }
     *     
     */
    public void setUihints(UIhints value) {
        this.uihints = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the hidden property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isHidden() {
        if (hidden == null) {
            return false;
        } else {
            return hidden;
        }
    }

    /**
     * Sets the value of the hidden property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHidden(Boolean value) {
        this.hidden = value;
    }

    /**
     * Gets the value of the toolType property.
     * 
     * @return
     *     possible object is
     *     {@link ToolTypeType }
     *     
     */
    public ToolTypeType getToolType() {
        return toolType;
    }

    /**
     * Sets the value of the toolType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToolTypeType }
     *     
     */
    public void setToolType(ToolTypeType value) {
        this.toolType = value;
    }

    /**
     * Gets the value of the urlMethod property.
     * 
     * @return
     *     possible object is
     *     {@link URLmethodType }
     *     
     */
    public URLmethodType getURLMethod() {
        return urlMethod;
    }

    /**
     * Sets the value of the urlMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link URLmethodType }
     *     
     */
    public void setURLMethod(URLmethodType value) {
        this.urlMethod = value;
    }
    
    //commenting this out, was in here for testing purposes, don't know if we
    //actually need it
//    @Override
//    public String toString() {
//        StringBuilder sb = new StringBuilder();
//        
//        sb.append(this.getId());
//        sb.append(this.getName());
//        sb.append(this.getCommand());
//        sb.append(this.getInputs());
//        
//        return sb.toString();
//    }

}
