//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.23 at 04:45:00 PM CDT 
//
package org.usd.edu.btl.betsconverter.GalaxyV1;

import java.nio.channels.Channel;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Inputs complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="Inputs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{}InputElement" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="action" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="check_values" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="method" type="{}URLmethodType" />
 *       &lt;attribute name="target" type="{}TargetType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Inputs", propOrder = {
    "inputElement"
})
public class Inputs {

    /**
     *
     */
    @XmlElements({
        @XmlElement(name = "param", type = Param.class),
        @XmlElement(name = "repeat", type = Repeat.class),
        @XmlElement(name = "conditional", type = Conditional.class),
        @XmlElement(name = "display", type = String.class)
    })
    protected List<Object> inputElement;

    /**
     *
     */
    @XmlAttribute(name = "action")
    protected String action;

    /**
     *
     */
    @XmlAttribute(name = "check_values")
    protected Boolean checkValues;

    /**
     *
     */
    @XmlAttribute(name = "method")
    protected URLmethodType method;

    /**
     *
     */
    @XmlAttribute(name = "target")
    protected TargetType target;

    /**
     * Gets the value of the inputElement property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the inputElement property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInputElement().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list null null null
     * null null     {@link Param }
     * {@link Repeat }
     * {@link Conditional }
     * {@link String }
     *
     *
     * @return
     */
    public List<Object> getInputElement() {
        if (inputElement == null) {
            inputElement = new ArrayList<Object>();
        }
        return this.inputElement;
    }

    /**
     *
     * @return
     */
    public List<Param> getInputElementParams() {
        List<Param> inputParams = new ArrayList<>();
        if (inputElement == null) {
            return inputParams;
        }
        for (int i = 0; i < inputElement.size(); i++) {
            if (inputElement.get(i).getClass() == Param.class) {
                inputParams.add((Param) inputElement.get(i));
            }
        }
        return inputParams;
    }

    /**
     *
     * @return
     */
    public List<Repeat> getInputElementRepeat() {
        List<Repeat> inputRepeat = new ArrayList<>();
        if (inputElement == null) {
            return inputRepeat;
        }
        for (int i = 0; i < inputElement.size(); i++) {
            if (inputElement.get(i).getClass() == Repeat.class) {
                inputRepeat.add((Repeat) inputElement.get(i));
            }
        }
        return inputRepeat;
    }

    /**
     *
     * @return
     */
    public List<Conditional> getInputElementConditional() {
        List<Conditional> inputCond = new ArrayList<>();
        if (inputElement == null) {
            return inputCond;
        }
        for (int i = 0; i < inputElement.size(); i++) {
            if (inputElement.get(i).getClass() == Conditional.class) {
                inputCond.add((Conditional) inputElement.get(i));
            }
        }
        return inputCond;
    }
  
    /**
     * Gets the value of the action property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the checkValues property.
     *
     * @return possible object is {@link Boolean }
     *
     */
    public Boolean isCheckValues() {
        return checkValues;
    }

    /**
     * Sets the value of the checkValues property.
     *
     * @param value allowed object is {@link Boolean }
     *
     */
    public void setCheckValues(Boolean value) {
        this.checkValues = value;
    }

    /**
     * Gets the value of the method property.
     *
     * @return possible object is {@link URLmethodType }
     *
     */
    public URLmethodType getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     *
     * @param value allowed object is {@link URLmethodType }
     *
     */
    public void setMethod(URLmethodType value) {
        this.method = value;
    }

    /**
     * Gets the value of the target property.
     *
     * @return possible object is {@link TargetType }
     *
     */
    public TargetType getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     *
     * @param value allowed object is {@link TargetType }
     *
     */
    public void setTarget(TargetType value) {
        this.target = value;
    }

}
