//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.23 at 04:45:00 PM CDT 
//


package org.usd.edu.btl.betsconverter.GalaxyV1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Options complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Options">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{}OptionsElement" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="from_dataset" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="from_file" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="from_data_table" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="from_parameter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="options_filter_attribute" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="transform_lines" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="startswith" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Options", propOrder = {
    "optionsElement"
})
public class Options {

    /**
     *
     */
    @XmlElements({
        @XmlElement(name = "filter", type = Filter.class),
        @XmlElement(name = "column", type = Column.class),
        @XmlElement(name = "validator", type = Validator.class),
        @XmlElement(name = "file", type = String.class)
    })
    protected List<Object> optionsElement;

    /**
     *
     */
    @XmlAttribute(name = "from_dataset")
    protected String fromDataset;

    /**
     *
     */
    @XmlAttribute(name = "from_file")
    protected String fromFile;

    /**
     *
     */
    @XmlAttribute(name = "from_data_table")
    protected String fromDataTable;

    /**
     *
     */
    @XmlAttribute(name = "from_parameter")
    protected String fromParameter;

    /**
     *
     */
    @XmlAttribute(name = "options_filter_attribute")
    protected String optionsFilterAttribute;

    /**
     *
     */
    @XmlAttribute(name = "transform_lines")
    protected String transformLines;

    /**
     *
     */
    @XmlAttribute(name = "startswith")
    protected String startswith;

    /**
     * Gets the value of the optionsElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the optionsElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOptionsElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Filter }
     * {@link Column }
     * {@link Validator }
     * {@link String }
     * 
     * 
     * @return 
     */
    public List<Object> getOptionsElement() {
        if (optionsElement == null) {
            optionsElement = new ArrayList<Object>();
        }
        return this.optionsElement;
    }

    /**
     * Gets the value of the fromDataset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromDataset() {
        return fromDataset;
    }

    /**
     * Sets the value of the fromDataset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromDataset(String value) {
        this.fromDataset = value;
    }

    /**
     * Gets the value of the fromFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromFile() {
        return fromFile;
    }

    /**
     * Sets the value of the fromFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromFile(String value) {
        this.fromFile = value;
    }

    /**
     * Gets the value of the fromDataTable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromDataTable() {
        return fromDataTable;
    }

    /**
     * Sets the value of the fromDataTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromDataTable(String value) {
        this.fromDataTable = value;
    }

    /**
     * Gets the value of the fromParameter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromParameter() {
        return fromParameter;
    }

    /**
     * Sets the value of the fromParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromParameter(String value) {
        this.fromParameter = value;
    }

    /**
     * Gets the value of the optionsFilterAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionsFilterAttribute() {
        return optionsFilterAttribute;
    }

    /**
     * Sets the value of the optionsFilterAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionsFilterAttribute(String value) {
        this.optionsFilterAttribute = value;
    }

    /**
     * Gets the value of the transformLines property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransformLines() {
        return transformLines;
    }

    /**
     * Sets the value of the transformLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransformLines(String value) {
        this.transformLines = value;
    }

    /**
     * Gets the value of the startswith property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartswith() {
        return startswith;
    }

    /**
     * Sets the value of the startswith property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartswith(String value) {
        this.startswith = value;
    }

}
