//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.23 at 04:45:00 PM CDT 
//
package org.usd.edu.btl.betsconverter.GalaxyV1;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Param complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Param">
 *   &lt;complexContent>
 *     &lt;extension base="{}InputType">
 *       &lt;sequence>
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="option" type="{}ParamOption" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="options" type="{}Options" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="validator" type="{}Validator" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="sanitizer" type="{}Sanitizer" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{}ParamType" />
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="help" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="optional" type="{http://www.w3.org/2001/XMLSchema}string" default="false" />
 *       &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="format" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="data_ref" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="accept_default" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="force_select" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="display" type="{}DisplayType" />
 *       &lt;attribute name="multiple" type="{}PermissiveBoolean" />
 *       &lt;attribute name="numerical" type="{}PermissiveBoolean" />
 *       &lt;attribute name="hierarchy" type="{}HierarchyType" />
 *       &lt;attribute name="checked" type="{}CheckedType" />
 *       &lt;attribute name="truevalue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="falsevalue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="metadata_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Param", propOrder = {
    "label",
    "option",
    "options",
    "validator",
    "sanitizer"
})
public class Param
    extends InputType
{

    /**
     *
     */
    protected String label;

    /**
     *
     */
    protected List<ParamOption> option;

    /**
     *
     */
    protected Options options;

    /**
     *
     */
    protected List<Validator> validator;

    /**
     *
     */
    protected Sanitizer sanitizer;

    /**
     *
     */
    @XmlAttribute(name = "type", required = true)
    protected ParamType type;

    /**
     *
     */
    @XmlAttribute(name = "label")
    protected String label1;

    /**
     *
     */
    @XmlAttribute(name = "help")
    protected String help;

    /**
     *
     */
    @XmlAttribute(name = "value")
    protected String value;

    /**
     *
     */
    @XmlAttribute(name = "optional")
    protected String optional;

    /**
     *
     */
    @XmlAttribute(name = "min")
    protected BigInteger min;

    /**
     *
     */
    @XmlAttribute(name = "max")
    protected BigInteger max;

    /**
     *
     */
    @XmlAttribute(name = "format")
    protected String format;

    /**
     *
     */
    @XmlAttribute(name = "data_ref")
    protected String dataRef;

    /**
     *
     */
    @XmlAttribute(name = "accept_default")
    protected Boolean acceptDefault;

    /**
     *
     */
    @XmlAttribute(name = "force_select")
    protected Boolean forceSelect;

    /**
     *
     */
    @XmlAttribute(name = "display")
    protected DisplayType display;

    /**
     *
     */
    @XmlAttribute(name = "multiple")
    protected String multiple;

    /**
     *
     */
    @XmlAttribute(name = "numerical")
    protected String numerical;

    /**
     *
     */
    @XmlAttribute(name = "hierarchy")
    protected HierarchyType hierarchy;

    /**
     *
     */
    @XmlAttribute(name = "checked")
    protected String checked;

    /**
     *
     */
    @XmlAttribute(name = "truevalue")
    protected String truevalue;

    /**
     *
     */
    @XmlAttribute(name = "falsevalue")
    protected String falsevalue;

    /**
     *
     */
    @XmlAttribute(name = "size")
    protected Integer size;

    /**
     *
     */
    @XmlAttribute(name = "metadata_name")
    protected String metadataName;

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the option property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the option property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOption().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParamOption }
     * 
     * 
     * @return 
     */
    public List<ParamOption> getOption() {
        if (option == null) {
            option = new ArrayList<ParamOption>();
        }
        return this.option;
    }

    /**
     * Gets the value of the options property.
     * 
     * @return
     *     possible object is
     *     {@link Options }
     *     
     */
    public Options getOptions() {
        return options;
    }

    /**
     * Sets the value of the options property.
     * 
     * @param value
     *     allowed object is
     *     {@link Options }
     *     
     */
    public void setOptions(Options value) {
        this.options = value;
    }

    /**
     * Gets the value of the validator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Validator }
     * 
     * 
     * @return 
     */
    public List<Validator> getValidator() {
        if (validator == null) {
            validator = new ArrayList<Validator>();
        }
        return this.validator;
    }

    /**
     * Gets the value of the sanitizer property.
     * 
     * @return
     *     possible object is
     *     {@link Sanitizer }
     *     
     */
    public Sanitizer getSanitizer() {
        return sanitizer;
    }

    /**
     * Sets the value of the sanitizer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sanitizer }
     *     
     */
    public void setSanitizer(Sanitizer value) {
        this.sanitizer = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ParamType }
     *     
     */
    public ParamType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParamType }
     *     
     */
    public void setType(ParamType value) {
        this.type = value;
    }

    /**
     * Gets the value of the label1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel1() {
        return label1;
    }

    /**
     * Sets the value of the label1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel1(String value) {
        this.label1 = value;
    }

    /**
     * Gets the value of the help property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelp() {
        return help;
    }

    /**
     * Sets the value of the help property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelp(String value) {
        this.help = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the optional property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptional() {
        if (optional == null) {
            return "false";
        } else {
            return optional;
        }
    }

    /**
     * Sets the value of the optional property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptional(String value) {
        this.optional = value;
    }

    /**
     * Gets the value of the min property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMin() {
        return min;
    }

    /**
     * Sets the value of the min property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMin(BigInteger value) {
        this.min = value;
    }

    /**
     * Gets the value of the max property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMax() {
        return max;
    }

    /**
     * Sets the value of the max property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMax(BigInteger value) {
        this.max = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the dataRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataRef() {
        return dataRef;
    }

    /**
     * Sets the value of the dataRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataRef(String value) {
        this.dataRef = value;
    }

    /**
     * Gets the value of the acceptDefault property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAcceptDefault() {
        return acceptDefault;
    }

    /**
     * Sets the value of the acceptDefault property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAcceptDefault(Boolean value) {
        this.acceptDefault = value;
    }

    /**
     * Gets the value of the forceSelect property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isForceSelect() {
        return forceSelect;
    }

    /**
     * Sets the value of the forceSelect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setForceSelect(Boolean value) {
        this.forceSelect = value;
    }

    /**
     * Gets the value of the display property.
     * 
     * @return
     *     possible object is
     *     {@link DisplayType }
     *     
     */
    public DisplayType getDisplay() {
        return display;
    }

    /**
     * Sets the value of the display property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisplayType }
     *     
     */
    public void setDisplay(DisplayType value) {
        this.display = value;
    }

    /**
     * Gets the value of the multiple property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultiple() {
        return multiple;
    }

    /**
     * Sets the value of the multiple property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultiple(String value) {
        this.multiple = value;
    }

    /**
     * Gets the value of the numerical property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumerical() {
        return numerical;
    }

    /**
     * Sets the value of the numerical property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumerical(String value) {
        this.numerical = value;
    }

    /**
     * Gets the value of the hierarchy property.
     * 
     * @return
     *     possible object is
     *     {@link HierarchyType }
     *     
     */
    public HierarchyType getHierarchy() {
        return hierarchy;
    }

    /**
     * Sets the value of the hierarchy property.
     * 
     * @param value
     *     allowed object is
     *     {@link HierarchyType }
     *     
     */
    public void setHierarchy(HierarchyType value) {
        this.hierarchy = value;
    }

    /**
     * Gets the value of the checked property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChecked() {
        return checked;
    }

    /**
     * Sets the value of the checked property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChecked(String value) {
        this.checked = value;
    }

    /**
     * Gets the value of the truevalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTruevalue() {
        return truevalue;
    }

    /**
     * Sets the value of the truevalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTruevalue(String value) {
        this.truevalue = value;
    }

    /**
     * Gets the value of the falsevalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFalsevalue() {
        return falsevalue;
    }

    /**
     * Sets the value of the falsevalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFalsevalue(String value) {
        this.falsevalue = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSize(Integer value) {
        this.size = value;
    }

    /**
     * Gets the value of the metadataName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetadataName() {
        return metadataName;
    }

    /**
     * Sets the value of the metadataName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetadataName(String value) {
        this.metadataName = value;
    }

}
