//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.23 at 04:45:00 PM CDT 
//

package org.usd.edu.btl.betsconverter.GalaxyV1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ValidatorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ValidatorType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="expression"/>
 *     &lt;enumeration value="regex"/>
 *     &lt;enumeration value="in_range"/>
 *     &lt;enumeration value="length"/>
 *     &lt;enumeration value="metadata"/>
 *     &lt;enumeration value="unspecified_build"/>
 *     &lt;enumeration value="no_options"/>
 *     &lt;enumeration value="empty_field"/>
 *     &lt;enumeration value="dataset_metadata_in_file"/>
 *     &lt;enumeration value="dataset_ok_validator"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ValidatorType")
@XmlEnum
public enum ValidatorType {

    /**
     *
     */
    @XmlEnumValue("expression")
    EXPRESSION("expression"),

    /**
     *
     */
    @XmlEnumValue("regex")
    REGEX("regex"),

    /**
     *
     */
    @XmlEnumValue("in_range")
    IN_RANGE("in_range"),

    /**
     *
     */
    @XmlEnumValue("length")
    LENGTH("length"),

    /**
     *
     */
    @XmlEnumValue("metadata")
    METADATA("metadata"),

    /**
     *
     */
    @XmlEnumValue("unspecified_build")
    UNSPECIFIED_BUILD("unspecified_build"),

    /**
     *
     */
    @XmlEnumValue("no_options")
    NO_OPTIONS("no_options"),

    /**
     *
     */
    @XmlEnumValue("empty_field")
    EMPTY_FIELD("empty_field"),

    /**
     *
     */
    @XmlEnumValue("dataset_metadata_in_file")
    DATASET_METADATA_IN_FILE("dataset_metadata_in_file"),

    /**
     *
     */
    @XmlEnumValue("dataset_ok_validator")
    DATASET_OK_VALIDATOR("dataset_ok_validator");
    private final String value;

    ValidatorType(String v) {
        value = v;
    }

    /**
     *
     * @return
     */
    public String value() {
        return value;
    }

    /**
     *
     * @param v
     * @return
     */
    public static ValidatorType fromValue(String v) {
        for (ValidatorType c: ValidatorType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
