//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.23 at 04:45:00 PM CDT 
//

package org.usd.edu.btl.betsconverter.GalaxyV1;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Validator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Validator">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type" use="required" type="{}ValidatorType" />
 *       &lt;attribute name="message" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="filename" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="metadata_name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="metadata_column" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="line_startswith" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="split" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Validator")
public class Validator {

    /**
     *
     */
    @XmlAttribute(name = "type", required = true)
    protected ValidatorType type;

    /**
     *
     */
    @XmlAttribute(name = "message")
    protected String message;

    /**
     *
     */
    @XmlAttribute(name = "filename")
    protected String filename;

    /**
     *
     */
    @XmlAttribute(name = "metadata_name")
    protected String metadataName;

    /**
     *
     */
    @XmlAttribute(name = "metadata_column")
    protected BigInteger metadataColumn;

    /**
     *
     */
    @XmlAttribute(name = "line_startswith")
    protected String lineStartswith;

    /**
     *
     */
    @XmlAttribute(name = "min")
    protected BigDecimal min;

    /**
     *
     */
    @XmlAttribute(name = "max")
    protected BigDecimal max;

    /**
     *
     */
    @XmlAttribute(name = "split")
    protected String split;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ValidatorType }
     *     
     */
    public ValidatorType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidatorType }
     *     
     */
    public void setType(ValidatorType value) {
        this.type = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the filename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilename() {
        return filename;
    }

    /**
     * Sets the value of the filename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilename(String value) {
        this.filename = value;
    }

    /**
     * Gets the value of the metadataName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetadataName() {
        return metadataName;
    }

    /**
     * Sets the value of the metadataName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetadataName(String value) {
        this.metadataName = value;
    }

    /**
     * Gets the value of the metadataColumn property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMetadataColumn() {
        return metadataColumn;
    }

    /**
     * Sets the value of the metadataColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMetadataColumn(BigInteger value) {
        this.metadataColumn = value;
    }

    /**
     * Gets the value of the lineStartswith property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineStartswith() {
        return lineStartswith;
    }

    /**
     * Sets the value of the lineStartswith property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineStartswith(String value) {
        this.lineStartswith = value;
    }

    /**
     * Gets the value of the min property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMin() {
        return min;
    }

    /**
     * Sets the value of the min property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMin(BigDecimal value) {
        this.min = value;
    }

    /**
     * Gets the value of the max property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMax() {
        return max;
    }

    /**
     * Sets the value of the max property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMax(BigDecimal value) {
        this.max = value;
    }

    /**
     * Gets the value of the split property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSplit() {
        return split;
    }

    /**
     * Sets the value of the split property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSplit(String value) {
        this.split = value;
    }

}
